export  default {
    issuekey:{
        fieldName:'key',
        path:'key'
    },
    summary:{
        fieldName:'summary',
        path:'fields.summary'
    },
    issuetype:{
        fieldName:'issuetype',
        path:'fields.issuetype.name'
    },
    status: {
        fieldName:'status',
        path:'fields.status.name'
    },
    serviceArea:{
        fieldName:'customfield_11306',
        path:'fields.customfield_11306.0.value',

    },
    labels:{
        fieldName:'labels',
        path:'fields.labels',
    },
    epicLink:{
        fieldName:'customfield_11200',
        path:'fields.customfield_11200'
    },
    project:{
        path:'fields.labels',
        parser:{
            type:"string",
            match:"regex",
            filter:'^[#*+_]'
        }
    },
    program:{
        path:'fields.labels',
        parser:{
            match:"in",
            filter:'["$CnSS","$FaTS","$SuS"]'
        }
    },
    iteration:{
        path:'fields.labels',
        parser:{
            match:"in",
            filter:'["$PI3.1","$PI3.2","$PI3.3","$PI3.4","$PI3.5", "$PI3.6"]'
        }
    },
    portfolio:{
        field:"project",
        parser:{
            match:"category",
            filter:[
                {filter:"^#",name:"Start Cost"},
                {filter:"^[*]",name:"PMR"},
                {filter:"^[+]",name:"Internal"},
                {filter:"^_",name:"R&D"}
            ]
        }
    }
};